# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-20 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160320_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='referral',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Profile'),
        ),
    ]
