# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-03 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='referral',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(height_field=320, null=True, upload_to='avatars/%d/%m/%Y', verbose_name='аватар', width_field=240),
        ),
    ]
